#' Build reproducible R code string for an exploration plot
#'
#' Assembles a character string of valid R code that recreates the current
#' exploration plot and exports it as PNG and interactive HTML.
#'
#' @param plot_type Character; either "individual" or "mean".
#' @param inputs List of current sidebar input values.
#' @param pknca_data A PKNCAdata object (used to extract column names).
#'
#' @return A single character string of R code.
build_plot_code <- function(plot_type, inputs, pknca_data) {
  # Extract PKNCA column metadata
  conc_col <- pknca_data$conc$columns$concentration
  time_col <- pknca_data$conc$columns$time
  concu_col <- pknca_data$conc$columns$concu
  timeu_col <- pknca_data$conc$columns$timeu
  subject_col <- pknca_data$conc$columns$subject

  # Format helper: quote a character vector for code output
  fmt_chr <- function(x) {
    if (is.null(x) || length(x) == 0) return("NULL")
    if (length(x) == 1) return(paste0('"', x, '"'))
    paste0('c(', paste0('"', x, '"', collapse = ", "), ')')
  }

  fmt_lgl <- function(x) {
    if (is.null(x) || !is.logical(x)) return("FALSE")
    if (x) "TRUE" else "FALSE"
  }

  fmt_num <- function(x) {
    if (is.null(x) || length(x) == 0 || all(!is.finite(x))) return("NULL")
    if (length(x) == 1) return(as.character(x))
    paste0("c(", paste(x, collapse = ", "), ")")
  }

  # Build filtering code
  filter_code <- ""
  fl <- inputs$filtering_list
  if (!is.null(fl) && length(fl) > 0) {
    filter_lines <- vapply(names(fl), function(col) {
      vals <- fmt_chr(fl[[col]])
      paste0('  ', col, ' = ', vals)
    }, character(1))
    filter_code <- paste0(
      "filtering_list <- list(\n",
      paste(filter_lines, collapse = ",\n"),
      "\n)"
    )
  } else {
    filter_code <- "filtering_list <- NULL"
  }

  # Determine threshold
  threshold_code <- fmt_num(inputs$threshold_value)

  # Build the plot function call
  if (plot_type == "individual") {
    plot_call <- paste0(
      'p <- aNCA::exploration_individualplot(\n',
      '  pknca_data = pknca_data,\n',
      '  color_by = ', fmt_chr(inputs$color_by), ',\n',
      '  facet_by = ', fmt_chr(inputs$facet_by), ',\n',
      '  show_facet_n = ', fmt_lgl(inputs$show_facet_n), ',\n',
      '  ylog_scale = ', fmt_lgl(inputs$ylog_scale), ',\n',
      '  show_legend = ', fmt_lgl(inputs$show_legend), ',\n',
      '  show_dose = ', fmt_lgl(inputs$show_dose), ',\n',
      '  threshold_value = ', threshold_code, ',\n',
      '  x_limits = ', fmt_num(inputs$x_limits), ',\n',
      '  y_limits = ', fmt_num(inputs$y_limits), ',\n',
      '  filtering_list = filtering_list,\n',
      '  use_time_since_last_dose = ',
      fmt_lgl(inputs$use_time_since_last_dose), ',\n',
      '  palette = ', fmt_chr(inputs$palette), ',\n',
      '  line_type = ', fmt_chr(inputs$y_axis_values), '\n',
      ')'
    )
  } else {
    plot_call <- paste0(
      'p <- aNCA::exploration_meanplot(\n',
      '  pknca_data = pknca_data,\n',
      '  color_by = ', fmt_chr(inputs$color_by), ',\n',
      '  facet_by = ', fmt_chr(inputs$facet_by), ',\n',
      '  show_facet_n = ', fmt_lgl(inputs$show_facet_n), ',\n',
      '  ylog_scale = ', fmt_lgl(inputs$ylog_scale), ',\n',
      '  show_legend = ', fmt_lgl(inputs$show_legend), ',\n',
      '  show_dose = ', fmt_lgl(inputs$show_dose), ',\n',
      '  threshold_value = ', threshold_code, ',\n',
      '  x_limits = ', fmt_num(inputs$x_limits), ',\n',
      '  y_limits = ', fmt_num(inputs$y_limits), ',\n',
      '  sd_min = ', fmt_lgl(inputs$sd_min), ',\n',
      '  sd_max = ', fmt_lgl(inputs$sd_max), ',\n',
      '  ci = ', fmt_lgl(inputs$ci), ',\n',
      '  filtering_list = filtering_list,\n',
      '  use_time_since_last_dose = ',
      fmt_lgl(inputs$use_time_since_last_dose), ',\n',
      '  palette = ', fmt_chr(inputs$palette), ',\n',
      '  line_type = ', fmt_chr(inputs$y_axis_values), '\n',
      ')'
    )
  }

  # Assemble full script
  paste0(
    '# Reproducible plot code generated by aNCA\n',
    '# Requires: aNCA, ggplot2, plotly, htmlwidgets\n',
    '\n',
    '# NOTE: Replace this with your own PKNCAdata object\n',
    '# pknca_data <- <your PKNCAdata object>\n',
    '\n',
    '# Filtering\n',
    filter_code, '\n',
    '\n',
    '# Generate plot\n',
    plot_call, '\n',
    '\n',
    '# Export as PNG\n',
    'ggplot2::ggsave("plot.png", plot = p, width = 10, height = 6, dpi = 300)\n',
    '\n',
    '# Export as interactive HTML\n',
    'p_interactive <- plotly::ggplotly(p)\n',
    'htmlwidgets::saveWidget(p_interactive, "plot.html", selfcontained = TRUE)\n'
  )
}
