# Auto-analysis script template
# Generated by aNCA auto-analysis — all settings_list$... placeholders
# are substituted with literal R values before execution.

library(aNCA)
library(dplyr)

## Load raw data ################################################
adnca_data <- read_pk(data_path)

## Preprocess data & create PKNCA object ########################
mapping <- settings_list$mapping
applied_filters <- settings_list$applied_filters
time_duplicate_rows <- settings_list$time_duplicate_rows

int_parameters <- settings_list$settings$int_parameters
units_table <- settings_list$units_table
parameters_selected_per_study <- settings_list$settings$parameters$selections
extra_vars_to_keep <- settings_list$extra_vars_to_keep
slope_rules <- settings_list$slope_rules

pknca_obj <- adnca_data %>%

  # Preprocess raw data and create the PKNCA object
  PKNCA_create_data_object(
    mapping = mapping,
    applied_filters = applied_filters,
    time_duplicate_rows = time_duplicate_rows
  ) %>%

  # Setup NCA settings, intervals, parameter selections, and units
  PKNCA_update_data_object(
    method = settings_list$settings$method,
    selected_analytes = settings_list$settings$analyte,
    selected_profile = settings_list$settings$profile,
    selected_pcspec = settings_list$settings$pcspec,
    start_impute = settings_list$settings$data_imputation$impute_c0,
    exclusion_list = settings_list$settings$general_exclusions,
    hl_adj_rules = slope_rules,
    keep_interval_cols = setdiff(extra_vars_to_keep, c("DOSEA", "ATPTREF", "ROUTE")),
    parameter_selections = parameters_selected_per_study,
    int_parameters = int_parameters,
    custom_units_table = units_table
  )

## Run NCA calculations ########################################
flag_rules <- settings_list$settings$flags
ratio_table <- settings_list$ratio_table
blq_rule <- settings_list$settings$data_imputation$blq_imputation_rule

pknca_res <- pknca_obj %>%

  # Run pk.nca and join subject and dose information to the results
  PKNCA_calculate_nca(
    blq_rule = blq_rule
  ) %>%

  # Add bioavailability results if requested
  add_f_to_pknca_results(settings_list$settings$bioavailability) %>%

  # Apply standard CDISC names
  mutate(PPTESTCD = translate_terms(PPTESTCD, "PKNCA", "PPTESTCD")) %>%

  # Flag relevant parameters based on AUCPEO, AUCPEP & lambda span
  PKNCA_hl_rules_exclusion(
    rules = flag_rules %>%
      purrr::keep(\(x) x$is.checked) %>%
      purrr::map(\(x) x$threshold)
  ) %>%

  # Derive secondary parameters (ratio parameters)
  calculate_table_ratios(ratio_table) %>%

  # Filter only parameters that have been requested
  remove_pp_not_requested()

## Obtain PP, ADPP, ADNCA & Pivoted results #####################
cdisc_datasets <- pknca_res %>%
  export_cdisc(grouping_vars = extra_vars_to_keep)

pivoted_results <- pivot_wider_pknca_results(
  myres = pknca_res,
  flag_rules = flag_rules,
  extra_vars_to_keep = extra_vars_to_keep
)

## Collect all outputs into a single list #######################
auto_results <- list(
  nca_results = list(
    nca_pkparam = pivoted_results
  ),
  CDISC = cdisc_datasets
)
