#' Generate a Unified Line Plot for PK Data
#'
#' This function creates a ggplot2 line plot for pharmacokinetic (PK) data.
#' It is designed to be flexible and can generate plots for both individual
#' concentration-time profiles and mean concentration-time profiles. The function
#' supports various customizations including log scales, faceting, error bars (for mean plots),
#' and threshold lines.
#'
#' @section Plot Types:
#' The function's behavior changes based on the arguments provided, for two main plot types:
#' \itemize{
#'   \item \strong{Individual Plots}:
#'     Set `x_var = "time_var"`, `y_var = "AVAL"` and `group_var = "USUBJID"`.
#'     The input `data` should be from `process_data_individual`.
#'   \item \strong{Mean Plots}:
#'     Set `x_var = "time_var"`, `y_var = "Mean"`, and `group_var = "color_var"`.
#'     The input `data` should be from `process_data_mean`. The arguments `show_sd_min`,
#'     `show_sd_max`, and `show_ci` are only applicable to this plot type.
#' }
#'
#' @param data A data.frame containing the data to be plotted. This should be
#'   pre-processed by either `process_data_individual` or `process_data_mean`.
#' @param x_var A character string specifying the column name for the x-axis.
#' @param y_var A character string specifying the column name for the y-axis.
#' @param group_var A character string specifying the column name used to group
#'   the lines, ensuring `geom_line` connects the correct points.
#' @param colorby_var A character vector specifying the column(s) from the original
#'   dataset that are used to determine the color of the lines and points.
#' @param facet_by A character vector of column names to facet the plot by.
#'   Default is `NULL` for no faceting.
#' @param ylog_scale A logical value (`TRUE` or `FALSE`) indicating whether to use
#'  a logarithmic scale for the y-axis.
#' @param show_threshold A logical value (`TRUE` or `FALSE`) indicating whether to
#'   display a horizontal threshold line.
#' @param threshold_value A numeric value for the y-intercept of the threshold line.
#'   Only used if `show_threshold` is `TRUE`.
#' @param show_dose A logical value (`TRUE` or `FALSE`) indicating whether to show
#'   vertical lines at dosing times.
#' @param dose_data An optional data.frame containing dosing information.
#'   It is required if `show_dose` is `TRUE`. The data frame must contain the faceting variables
#'   (if any are used) and a `TIME_DOSE` column for the x-intercepts.
#' @param palette An optional named character vector of colors for the plot. The names should
#'   correspond to the levels of the `color_var` in the `data`. This is typically
#'   generated by `get_persistent_palette`.
#' @param show_sd_min A logical value (`TRUE` or `FALSE`). If `TRUE`, plots the lower
#'   standard deviation error bars. (Only for mean plots).
#' @param show_sd_max A logical value (`TRUE` or `FALSE`). If `TRUE`, plots the upper
#'   standard deviation error bars. (Only for mean plots).
#' @param show_ci A logical value (`TRUE` or `FALSE`). If `TRUE`, plots a 95%
#'   confidence interval ribbon. (Only for mean plots).
#' @param tooltip_vars Character vector of column names to include in the tooltip.
#' @param labels_df A data.frame for variable label lookups.
#'
#' @returns A `ggplot` object representing the line plot.
#'
#' @import ggplot2
#' @import dplyr
#' @export
g_lineplot <- function(data,
                       x_var,
                       y_var,
                       group_var,
                       colorby_var,
                       facet_by = NULL,
                       ylog_scale = FALSE,
                       show_threshold = FALSE,
                       threshold_value = 0,
                       show_dose = FALSE,
                       dose_data = NULL,
                       palette = NULL,
                       show_sd_min = FALSE,
                       show_sd_max = FALSE,
                       show_ci = FALSE,
                       tooltip_vars = NULL,
                       labels_df = NULL) {

  # Set up plot labels - assumes individual plot unless mean columns are present
  is_mean_plot <- all(c("Mean", "SD", "N") %in% names(data))

  # Defensively set mean-plot flags to FALSE if it's not a mean plot
  if (!is_mean_plot) {
    show_sd_min <- FALSE
    show_sd_max <- FALSE
    show_ci     <- FALSE
  }

  if (is_mean_plot) {
    x_lab <- paste0("Nominal Time [", unique(data$RRLTU), "]")
    y_lab <- paste0("Mean Concentration [", unique(data$AVALU), "]")
    title <- "Mean PK Concentration - Time Profile"
  } else {
    x_lab <- paste0("Time [", unique(data$RRLTU), "]")
    y_lab <- paste0("Concentration [", unique(data$AVALU), "]")
    title <- "PK Concentration - Time Profile"
  }

  # --- Tooltip Construction ---
  if (nrow(data) == 0) {
    data$tooltip_text <- character(0)
  }

  if (!is.null(tooltip_vars)) {
    if (!is.null(labels_df)) {
      # Generate tooltip if labels_df available
      data$tooltip_text <- generate_tooltip_text(data, labels_df, tooltip_vars, "ADNCA")
    } else {
      # Fallback to simple paste if labels_df is missing
      valid_vars <- intersect(tooltip_vars, names(data))
      if (length(valid_vars) > 0) {
        parts <- lapply(valid_vars, function(v) paste0(v, ": ", data[[v]]))
        data$tooltip_text <- do.call(paste, c(parts, sep = "<br>"))
      } else {
        data$tooltip_text <- rep(NA_character_, nrow(data))
      }
    }
  } else {
    data$tooltip_text <- rep(NA_character_, nrow(data))
  }

  plt <- ggplot(data, aes(
    x = .data[[x_var]],
    y = .data[[y_var]],
    color = color_var,
    group = .data[[group_var]],
    text = tooltip_text
  )) +
    geom_line() +
    geom_point() +
    labs(
      x = x_lab,
      y = y_lab,
      title = title,
      color = paste(colorby_var, collapse = ", ")
    ) +
    theme_bw()

  # Add optional layers
  optional_layers <- list(
    .add_palette(palette),
    .add_y_scale(ylog_scale),
    .add_faceting(facet_by),
    .add_threshold(show_threshold, threshold_value),
    .add_dose_lines(show_dose, dose_data, facet_by),
    .add_mean_layers(
      is_mean_plot,
      show_sd_min,
      show_sd_max,
      show_ci,
      colorby_var,
      y_var,
      x_var,
      group_var
    )
  )

  return(plt + optional_layers)
}

# --- Helper Functions (Internal) ---
# These functions contain the optional layers logic

#' @noRd
.add_palette <- function(palette) {
  if (is.null(palette)) {
    return(NULL)
  }
  scale_color_manual(values = palette)
}

#' @noRd
.add_y_scale <- function(ylog_scale) {
  if (!ylog_scale) {
    return(NULL)
  }
  scale_y_log10(breaks = c(0.001, 0.01, 0.1, 1, 10, 100, 1000), labels = scales::comma)
}

#' @noRd
.add_faceting <- function(facet_by) {
  if (is.null(facet_by) || length(facet_by) == 0) {
    return(NULL)
  }
  facet_wrap(vars(!!!syms(facet_by)), scales = "free")
}

#' @noRd
.add_threshold <- function(show_threshold, threshold_value) {
  if (!isTRUE(show_threshold)) {
    return(NULL)
  }
  geom_hline(yintercept = threshold_value, linetype = "dotted", color = "red")
}

#' @noRd
.add_dose_lines <- function(show_dose, dose_data, facet_by) {
  if (!isTRUE(show_dose)) {
    return(NULL)
  }

  dose_info <- dose_data %>%
    select(all_of(unique(c(facet_by, "TIME_DOSE", "DOSEA")))) %>%
    distinct() %>%
    filter(!is.na(TIME_DOSE))

  geom_vline(data = dose_info, aes(xintercept = TIME_DOSE), linetype = "dotted", color = "grey")
}

#' @noRd
.add_mean_layers <- function(is_mean_plot, show_sd_min, show_sd_max,
                             show_ci, colorby_var, y_var, x_var, group_var) {
  if (!is_mean_plot) {
    return(NULL)
  }

  # 1. Error bars
  error_bar_layer <- if (isTRUE(show_sd_min) || isTRUE(show_sd_max)) {
    ymin_val <- if (isTRUE(show_sd_min)) sym("SD_min") else sym(y_var)
    ymax_val <- if (isTRUE(show_sd_max)) sym("SD_max") else sym(y_var)

    geom_errorbar(
      aes(
        x = .data[[x_var]],
        ymin = !!ymin_val,
        ymax = !!ymax_val,
        color = color_var,
        group = .data[[group_var]]
      ),
      inherit.aes = FALSE,
      width = 0.4
    )
  } else {
    NULL
  }

  # 2. CI Ribbon
  ci_ribbon_layer <- if (isTRUE(show_ci)) {
    list(
      geom_ribbon(aes(ymin = CI_lower, ymax = CI_upper, fill = color_var), alpha = 0.3),
      guides(fill = "none"),
      labs(color = paste0(paste(colorby_var, collapse = ", "), " (95% CI)"))
    )
  } else {
    NULL
  }

  # Return a list of all layers
  list(error_bar_layer, ci_ribbon_layer)
}
