#' Generate a Unified Line Plot for PK Data
#'
#' This function creates a ggplot2 line plot for pharmacokinetic (PK) data.
#' It is designed to be flexible and can generate plots for both individual
#' concentration-time profiles and mean concentration-time profiles. The function
#' supports various customizations including log scales, faceting, error bars (for mean plots),
#' and threshold lines.
#'
#' @section Plot Types:
#' The function's behavior changes based on the arguments provided, accommodating two main plot types:
#' \itemize{
#'   \item \strong{Individual Plots}: Set `x_var = "time_var"`, `y_var = "AVAL"`, and `group_var = "USUBJID"`.
#'     The input `data` should be from `process_data_individual`.
#'   \item \strong{Mean Plots}: Set `x_var = "time_var"`, `y_var = "Mean"`, and `group_var = "color_var"`.
#'     The input `data` should be from `process_data_mean`. The arguments `show_sd_min`,
#'     `show_sd_max`, and `show_ci` are only applicable to this plot type.
#' }
#'
#' @param data A data.frame containing the data to be plotted. This should be
#'   pre-processed by either `process_data_individual` or `process_data_mean`.
#' @param x_var A character string specifying the column name for the x-axis. See the "Plot Types" section for examples.
#' @param y_var A character string specifying the column name for the y-axis. See the "Plot Types" section for examples.
#' @param group_var A character string specifying the column name used to group
#'   the lines, ensuring `geom_line` connects the correct points. See the "Plot Types" section for examples.
#' @param colorby_var A character vector specifying the column(s) from the original
#'   dataset that are used to determine the color of the lines and points.
#' @param facet_by A character vector of column names to facet the plot by (e.g., `c("PARAM", "DOSEA")`).
#'   Default is `NULL` for no faceting.
#' @param yaxis_scale A character string, either `"Lin"` (default) or `"Log"`, to set the
#'   y-axis scale.
#' @param show_threshold A logical value (`TRUE` or `FALSE`) indicating whether to
#'   display a horizontal threshold line.
#' @param threshold_value A numeric value for the y-intercept of the threshold line.
#'   Only used if `show_threshold` is `TRUE`.
#' @param show_dose A logical value (`TRUE` or `FALSE`) indicating whether to show
#'   vertical lines at dosing times.
#' @param dose_data An optional data.frame containing dosing information.
#'   It is required if `show_dose` is `TRUE`. The data frame must contain the faceting variables
#'   (if any are used) and a `TIME_DOSE` column for the x-intercepts.
#' @param palette An optional named character vector of colors for the plot. The names should
#'   correspond to the levels of the `color_var` in the `data`. This is typically
#'   generated by `get_persistent_palette`.
#' @param show_sd_min A logical value (`TRUE` or `FALSE`). If `TRUE`, plots the lower
#'   standard deviation error bars. (Only for mean plots).
#' @param show_sd_max A logical value (`TRUE` or `FALSE`). If `TRUE`, plots the upper
#'   standard deviation error bars. (Only for mean plots).
#' @param show_ci A logical value (`TRUE` or `FALSE`). If `TRUE`, plots a 95%
#'   confidence interval ribbon. (Only for mean plots).
#'
#' @returns A `ggplot` object representing the line plot.
#'
#' @import ggplot2
#' @import dplyr
#' @export
g_lineplot <- function(data,
                       x_var,
                       y_var,
                       group_var,
                       colorby_var,
                       facet_by = NULL,
                       yaxis_scale = "Lin",
                       show_threshold = FALSE,
                       threshold_value = 0,
                       show_dose = FALSE,
                       dose_data = NULL,
                       palette = NULL,
                       show_sd_min = FALSE,
                       show_sd_max = FALSE,
                       show_ci = FALSE) {
  
  # Set up plot labels - assumes individual plot unless mean columns are present
  is_mean_plot <- all(c("Mean", "SD", "N") %in% names(data))
  if (is_mean_plot) {
    x_lab <- paste0("Nominal Time [", unique(data$RRLTU), "]")
    y_lab <- paste0("Mean Concentration [", unique(data$AVALU), "]")
    title <- "Mean PK Concentration - Time Profile"
  } else {
    x_lab <- paste0("Time [", unique(data$RRLTU), "]")
    y_lab <- paste0("Concentration [", unique(data$AVALU), "]")
    title <- "PK Concentration - Time Profile"
  }
  
  plt <- ggplot(data, aes(
    x = .data[[x_var]],
    y = .data[[y_var]],
    color = color_var,
    group = .data[[group_var]]
  )) +
    geom_line() +
    geom_point() +
    labs(
      x = x_lab,
      y = y_lab,
      title = title,
      color = paste(colorby_var, collapse = ", ")
    ) +
    theme_bw()
  
  # Add optional layers
  if (!is.null(palette)) {
    plt <- plt + scale_color_manual(values = palette)
  }
  
  if (yaxis_scale == "log") {
    plt <- plt +
      scale_y_log10(breaks = c(0.001, 0.01, 0.1, 1, 10, 100, 1000), labels = scales::comma)
  }
  
  if (!is.null(facet_by) && length(facet_by) > 0) {
    plt <- plt + facet_wrap(vars(!!!syms(facet_by)), scales = "free")
  }
  
  if (isTRUE(show_threshold)) {
    plt <- plt + geom_hline(yintercept = threshold_value, linetype = "dotted", color = "red")
  }
  
  if (isTRUE(show_dose)) {
    dose_info <- dose_data %>%
      select(all_of(unique(c(facet_by, "TIME_DOSE", "DOSEA")))) %>%
      distinct() %>%
      filter(!is.na(TIME_DOSE))
    plt <- plt + geom_vline(data = dose_info, aes(xintercept = TIME_DOSE), linetype = "dotted", color = "grey")
  }
  
  # Mean plot specific layers
  if (is_mean_plot) {
    if (isTRUE(show_sd_min) || isTRUE(show_sd_max)) {
      ymin_val <- if (isTRUE(show_sd_min)) data$SD_min else data$Mean
      ymax_val <- if (isTRUE(show_sd_max)) data$SD_max else data$Mean
      plt <- plt + geom_errorbar(aes(ymin = ymin_val, ymax = ymax_val), width = 0.4)
    }
    if (isTRUE(show_ci)) {
      plt <- plt +
        geom_ribbon(aes(ymin = CI_lower, ymax = CI_upper, fill = color_var), alpha = 0.3) +
        guides(fill = "none") +
        labs(color = paste0(paste(colorby_var, collapse = ", "), " (95% CI)"))
    }
  }
  
  return(plt)
}
