#' Run the Shiny app
#' @param ... Arguments passed to `shiny::runApp()`
#' @export
run_app <- function(...) {
  require(aNCA)

  require(bslib)
  require(checkmate)
  require(dplyr)
  require(DT)
  require(forcats)
  require(ggh4x)
  require(ggplot2)
  require(glue)
  require(haven)
  require(htmlwidgets)
  require(logger)
  require(magrittr)
  require(nestcolor)
  require(PKNCA)
  require(plotly)
  require(purrr)
  require(reactable)
  require(reactable.extras)
  require(rio)
  require(rmarkdown)
  require(scales)
  require(shiny)
  require(shinyBS)
  require(shinycssloaders)
  require(shinyFiles)
  require(shinyjqui)
  require(shinyjs)
  require(shinyWidgets)
  require(stats)
  require(stringi)
  require(stringr)
  require(tern)
  require(tidyr)
  require(tools)
  require(utils)
  require(units)
  require(rlang)
  require(yaml)
  require(zip)
  shiny::runApp(system.file("shiny", package = "aNCA"), ...)
}
